name: 1. Cluster Common, Cluster Init, Project Init

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  java:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Run tests
        run: mvn clean test